config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "books#index"
  get '/dashboard', to: "pages#dashboard"
  delete "books/:id", to: "pages#destroy", as: :destroy_book
  delete "bookings/:id", to: "pages#destroy_booking", as: :destroy_booking

  resources :books do
    resources :bookings, only: :create
  end

  resources :bookings, only: [:edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :photo
  belongs_to :user
  has_many :bookings, dependent: :destroy

  validates :title, presence: true
  validates :description, presence: true
  validates :author, presence: true
  validates :year, presence: true
  validates :publisher, presence: true
  validates :price_per_day, presence: true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :starting_date, presence: true
  validates :ending_date, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bookings
  has_many :books

  # validates :nickname, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    @booking = Booking.new(booking_params)
    @booking.book = @book
    @booking.user_id = current_user.id

    if @booking.save
      redirect_to dashboard_path, notice: 'Réservation validée !'
    else
      redirect_to book_path(@book), notice: 'Vous devez indiquer les dates !'
    end
  end

  def edit
    @booking = Booking.find(params[:id])
    @book = @booking.book
    # @room = Room.find(params[:room_id])
    @booking.user_id = current_user.id
  end

  def update
    @booking = Booking.find(params[:id])
    @booking.update(booking_params)
    redirect_to dashboard_path
  end

  private

  def booking_params
    params.require(:booking).permit(:starting_date, :ending_date)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.all

    if params[:query].present?
      sql_query = "title ILIKE :query OR description ILIKE :query OR author ILIKE :query"
      @books = Book.where(sql_query, query: "%#{params[:query]}%")
    else
      @books = Book.all
    end
  end

  def show
    @book = Book.find(params[:id])
    @booking = Booking.new
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id

    if @book.save
      redirect_to @book, notice: 'Ton livre a été enregistré avec succès !'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    @book.update(book_params)
    redirect_to book_path(@book)
  end

  private

  def book_params
    params.require(:book).permit(:title, :description, :author, :year, :publisher, :price_per_day, :photo)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index ]

  def dashboard
    @books = current_user.books
    @bookings = current_user.bookings
  end


  def destroy_booking
  @booking = Booking.find(params[:id])
  @booking.destroy
  redirect_to dashboard_path, status: :see_other
  # suppression des books créer
  end

  def destroy
  @book = Book.find(params[:id])
  @book.destroy
  redirect_to dashboard_path, status: :see_other
  # suppression des réservations faites
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/edit.html.erb
<%= link_to "← Retour", root_path, class:"text-decoration-none text-dark ms-5 mt-2 mb-2 " %>

<div class='container mb-5'>

  <%# Titre et prix %>
  <div class="accroche">
    <h3><%= @book.title %></h3>
    <h4><%= @book.price_per_day %> € par jour</h4>
  </div>

  <%# card show %>
  <div class="card-show">
    <%# photo %>
    <div class="img-show">
      <%if @book.photo.attached? %>
        <%= cl_image_tag @book.photo.key, crop: :fill , height: 400 %>
      <% end %>
    </div>
    <%# contenu textuel %>
    <div class="text-show">
      <h5>Description</h5>
      <br>
      <%=@book.description%>
      <%# réservation date %>
      <%# <% if @book.user != current_user %>
        <div class="mt-5">
          <%= simple_form_for [@booking] do |f|%>
            <div class="booking-dates">
              <%= f.input :starting_date, as: :date, html5: true, label: 'De' %>
              <%= f.input :ending_date, as: :date, html5: true, label: 'à' %>
            </div>
            <%= f.submit 'Modifier ma réservation', class: "btn btn-primary"%>
          <% end %>
        <%# <%else%>
          <%# <div class="d-flex"> %>
            <%# <%= link_to 'Retour à mon espace',  dashboard_path, class: "btn btn-primary button" %>
            <%# <%= link_to 'Créer une autre annonce',  new_book_path, class: "btn btn-primary button" %>
          <%# </div> %>
        </div>
      <%# <%end%>
    </div>

  </div>



</div>

app/views/books/edit.html.erb
<h2 class="accroche">Modification de ta livre mise en location</h2>
<%= link_to "← Retour", root_path, class:"text-decoration-none text-dark ms-5 mt-2 mb-2 " %>

<div class="container">
  <div style="width: 60%" class="m-auto mt-3 mb-5">
    <%= simple_form_for(@book) do |f| %>
      <%= f.input :title, label: 'Titre', :input_html => { :class => 'bg-white' }%>
      <%= f.input :description, label: 'Description', :input_html => { :class => 'bg-white' } %>
      <%= f.input :author, label: 'Auteur', :input_html => { :class => 'bg-white' } %>
      <%= f.input :year, label: 'Année de publication', :input_html => { :class => 'bg-white' } %>
      <%= f.input :publisher,  label: 'Editeur', :input_html => { :class => 'bg-white' } %>
      <%= f.input :price_per_day,  label: 'Prix par jour', :input_html => { :class => 'bg-white' } %>
      <%= f.input :photo, as: :file,  label: 'La photo du livre', :input_html => { :class => 'bg-white' } %>
      <%= f.submit "Valider la modification", class: "btn btn-primary button", :input_html => { :class => 'bg-white' }%>
    <% end %>
  </div>
</div>

app/views/books/index.html.erb
  <%# text accroche %>
<div class="accroche">
  <h3>Besoin d'un peu de lecture ?</h3>
  <h3>Laisser vous tenter par les offres du moment à louer</h3>
  <%# barre de recherche %>
  <div class="my-5 mx-auto w-50">
    <%= form_with url: root_path, method: :get, class: "d-flex " do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control bg-white",
        placeholder: "Trouve un livre"
      %>
      <%= submit_tag "Rechercher", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

<div class='container mb-5'>
  <%# card offre en location %>
  <div class="grid-card">
    <% @books.each do |book| %>
      <% if book.user != current_user %>
        <div class="card-product">
          <div class="photo-book">
            <%if book.photo.attached? %>
              <%= cl_image_tag book.photo.key %>
            <% end %>
          </div>
          <div class="card-product-infos">
            <h2><strong><%= book.title %></strong></h2>
            <p>Description: <%= book.description %></p>
            <p>Auteur: <%= book.author %></p>
            <p>Année: <%= book.year %></p>
            <p>Editeur: <%= book.publisher %></p>
            <p>Prix par jour: <%= book.price_per_day %> €</p>
            <%= link_to 'Plus de détails', book_path(book), class: "btn btn-primary button" %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>

</div>

app/views/books/new.html.erb
  <h2 class="accroche">Mise en location de ton livre</h2>
<%= link_to "← Retour", root_path, class:"text-decoration-none text-dark ms-5 mt-2 mb-2 " %>

<div class="container mb-5">
  <div style="width: 60%" class="m-auto mt-3 mb-5">
    <%= simple_form_for(@book) do |f| %>
      <%= f.input :title, label: 'Titre', :input_html => { :class => 'bg-white' }%>
      <%= f.input :description, label: 'Description', :input_html => { :class => 'bg-white' } %>
      <%= f.input :author, label: 'Auteur', :input_html => { :class => 'bg-white' } %>
      <%= f.input :year, label: 'Année de publication', :input_html => { :class => 'bg-white' } %>
      <%= f.input :publisher,  label: 'Editeur', :input_html => { :class => 'bg-white' } %>
      <%= f.input :price_per_day,  label: 'Prix par jour', :input_html => { :class => 'bg-white' } %>
      <%= f.input :photo, as: :file,  label: 'La photo du livre', :input_html => { :class => 'bg-white' } %>
      <%= f.submit "Enregistrer", class: "btn btn-primary button", :input_html => { :class => 'bg-white' }%>
    <% end %>
  </div>
</div>

app/views/books/show.html.erb
<%= link_to "← Retour", root_path, class:"text-decoration-none text-dark ms-5 " %>

<div class='container mb-5'>

  <%# Titre et prix %>
  <div class="accroche">
    <h3><%= @book.title %></h3>
    <h4><%= @book.price_per_day %> € par jour</h4>
  </div>

  <%# card show %>
  <div class="card-show">
    <%# photo %>
    <div class="img-show">
      <%if @book.photo.attached? %>
        <%= cl_image_tag @book.photo.key, crop: :fill , height: 400 %>
      <% end %>
    </div>
    <%# contenu textuel %>
    <div class="text-show">
      <h5>Description</h5>
      <br>
      <%=@book.description%>
      <%# réservation date %>
      <% if @book.user != current_user %>
        <div class="mt-5">
          <%= simple_form_for [@book, @booking] do |f|%>
            <div class="booking-dates">
              <%= f.input :starting_date, as: :date, html5: true, label: 'De' %>
              <%= f.input :ending_date, as: :date, html5: true, label: 'à' %>
            </div>
            <%= f.submit 'Réserver', class: "btn btn-primary"%>
          <% end %>
        </div>
      <%end%>
    </div>

  </div>



</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookabook</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body><%= render "shared/navbar" %>
<%= render "shared/flashes" %>

    <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/dashboard.html.erb
<h2 class="accroche">Mon espace</h2>
<%= link_to "← Retour", root_path, class:"text-decoration-none text-dark ms-5 mt-2 mb-2 " %>
<div class="container">
  <h3 class="titre-dashboard">Vos réservations de livre</h3>

  <% if !@bookings.exists?() %>
    <div class="no-booking">
      <h5>Vous n'avez pas encore de réservation 🥲</h5>
      <h6> Pour consultez nos offres, cliquer <%= link_to "ici", root_path%></h6>
    </div>
  <%else %>
    <div class="grid-card">
        <% @bookings.each do |booking| %>
          <div class="card-product">
            <div class="photo-book">
              <%if booking.book.photo.attached? %>
                <%= cl_image_tag booking.book.photo.key %>
              <% end %>
            </div>
            <div class="card-product-infos">
              <h2><strong><%= booking.book.title %></strong></h2>
              <p>Du <%=booking.starting_date %> au <%=booking.ending_date %></p>
              <p><%= booking.book.description %></p>
              <p>Prix par jour: <%= booking.book.price_per_day %> €</p>
              <div class="d-flex">
                <%= link_to 'Modifier ma réservation',  edit_booking_path(booking), class: "btn btn-primary button" %>
                <%= link_to "🗑️", destroy_booking_path(booking), data: {turbo_method: :delete, turbo_confirm: "Etes-vous sur.e?"}, class: "supprimer"%>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <%end%>


  <h3 class="titre-dashboard">Vos offres de livre</h3>

  <% if !@books.exists?() %>
    <div class="no-booking">
      <h5>Vous n'avez pas encore d'annonce 🥲</h5>
      <h6> Pour ajouter une offre, cliquer <%= link_to "ici", new_book_path%></h6>
    </div>
  <%else %>
    <div class="grid-card">
      <% @books.each do |book| %>
          <div class="card-product">
            <div class="photo-book">
              <%if book.photo.attached? %>
                <%= cl_image_tag book.photo.key %>
              <% end %>
            </div>
            <div class="card-product-infos">
              <h2><strong><%= book.title %></strong></h2>
              <p>Description: <%= book.description %></p>
              <p>Auteur: <%= book.author %></p>
              <p>Année: <%= book.year %></p>
              <p>Editeur: <%= book.publisher %></p>
              <p>Prix par jour: <%= book.price_per_day %> €</p>
              <div class="d-flex ">
                <%= link_to 'Modifier mon offre', edit_book_path(book), class: "btn btn-primary button" %>
                <%= link_to "🗑️", book_path(book), data: {turbo_method: :delete, turbo_confirm: "Etes-vous sur.e?"}, class: "supprimer"%>
              </div>
            </div>
          </div>
        <% end %>
    </div>
  <% end %>
</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Book the book is made with <i class="fas fa-heart"></i> in Mougins
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand d-flex" do %>  <%# changement root_path %>
      <%= image_tag "https://res.cloudinary.com/dlumucj7m/image/upload/v1671362946/logo_padyfu.jpg" %> <%# changement logo %>
      <%# ajout du titre %>
      <h3 class="title-brand">Book a Book</h3>
    <% end %>


    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li>
            <%= link_to "Louez votre livre", new_book_path, class: "nav-link"%>
          </li>
          <li class="nav-item active">
            <%= link_to "Mon espace", dashboard_path, class: "nav-link" %>
          </li>

          <li class="nav-item dropdown">
            <%= image_tag "https://res.cloudinary.com/dlumucj7m/image/upload/v1671363030/photo_CV_fwwhqk.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          </li>
          <li>
            <%= link_to "Se déconnecter", destroy_user_session_path, data: {turbo_method: :delete}, class: "nav-link"%>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Se connecter", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>